/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.pn.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import org.pn.model.Medicine;

import org.pn.service.MedicineLocalServiceUtil;

/**
 * The extended model base implementation for the Medicine service. Represents a row in the &quot;hos_medicine&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MedicineImpl}.
 * </p>
 *
 * @author thuctap
 * @see MedicineImpl
 * @see org.pn.model.Medicine
 * @generated
 */
public abstract class MedicineBaseImpl extends MedicineModelImpl
	implements Medicine {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a medicine model instance should use the {@link Medicine} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			MedicineLocalServiceUtil.addMedicine(this);
		}
		else {
			MedicineLocalServiceUtil.updateMedicine(this);
		}
	}
}