/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.pn.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.pn.model.Patients;
import org.pn.model.PatientsModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Patients service. Represents a row in the &quot;hos_patient&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.pn.model.PatientsModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PatientsImpl}.
 * </p>
 *
 * @author thuctap
 * @see PatientsImpl
 * @see org.pn.model.Patients
 * @see org.pn.model.PatientsModel
 * @generated
 */
public class PatientsModelImpl extends BaseModelImpl<Patients>
	implements PatientsModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a patients model instance should use the {@link org.pn.model.Patients} interface instead.
	 */
	public static final String TABLE_NAME = "hos_patient";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_patient", Types.BIGINT },
			{ "name", Types.VARCHAR },
			{ "address", Types.VARCHAR },
			{ "phonenumber", Types.VARCHAR },
			{ "department", Types.VARCHAR },
			{ "symptoms", Types.VARCHAR },
			{ "gender", Types.VARCHAR },
			{ "id_doctor", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table hos_patient (id_patient LONG not null primary key,name VARCHAR(75) null,address VARCHAR(75) null,phonenumber VARCHAR(75) null,department VARCHAR(75) null,symptoms VARCHAR(75) null,gender VARCHAR(75) null,id_doctor LONG)";
	public static final String TABLE_SQL_DROP = "drop table hos_patient";
	public static final String ORDER_BY_JPQL = " ORDER BY patients.id_patient ASC";
	public static final String ORDER_BY_SQL = " ORDER BY hos_patient.id_patient ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.pn.model.Patients"), true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.pn.model.Patients"), true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.pn.model.Patients"));

	public PatientsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id_patient;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId_patient(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id_patient;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Patients.class;
	}

	@Override
	public String getModelClassName() {
		return Patients.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id_patient", getId_patient());
		attributes.put("name", getName());
		attributes.put("address", getAddress());
		attributes.put("phonenumber", getPhonenumber());
		attributes.put("department", getDepartment());
		attributes.put("symptoms", getSymptoms());
		attributes.put("gender", getGender());
		attributes.put("id_doctor", getId_doctor());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id_patient = (Long)attributes.get("id_patient");

		if (id_patient != null) {
			setId_patient(id_patient);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String address = (String)attributes.get("address");

		if (address != null) {
			setAddress(address);
		}

		String phonenumber = (String)attributes.get("phonenumber");

		if (phonenumber != null) {
			setPhonenumber(phonenumber);
		}

		String department = (String)attributes.get("department");

		if (department != null) {
			setDepartment(department);
		}

		String symptoms = (String)attributes.get("symptoms");

		if (symptoms != null) {
			setSymptoms(symptoms);
		}

		String gender = (String)attributes.get("gender");

		if (gender != null) {
			setGender(gender);
		}

		Long id_doctor = (Long)attributes.get("id_doctor");

		if (id_doctor != null) {
			setId_doctor(id_doctor);
		}
	}

	@Override
	public long getId_patient() {
		return _id_patient;
	}

	@Override
	public void setId_patient(long id_patient) {
		_id_patient = id_patient;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public String getAddress() {
		if (_address == null) {
			return StringPool.BLANK;
		}
		else {
			return _address;
		}
	}

	@Override
	public void setAddress(String address) {
		_address = address;
	}

	@Override
	public String getPhonenumber() {
		if (_phonenumber == null) {
			return StringPool.BLANK;
		}
		else {
			return _phonenumber;
		}
	}

	@Override
	public void setPhonenumber(String phonenumber) {
		_phonenumber = phonenumber;
	}

	@Override
	public String getDepartment() {
		if (_department == null) {
			return StringPool.BLANK;
		}
		else {
			return _department;
		}
	}

	@Override
	public void setDepartment(String department) {
		_department = department;
	}

	@Override
	public String getSymptoms() {
		if (_symptoms == null) {
			return StringPool.BLANK;
		}
		else {
			return _symptoms;
		}
	}

	@Override
	public void setSymptoms(String symptoms) {
		_symptoms = symptoms;
	}

	@Override
	public String getGender() {
		if (_gender == null) {
			return StringPool.BLANK;
		}
		else {
			return _gender;
		}
	}

	@Override
	public void setGender(String gender) {
		_gender = gender;
	}

	@Override
	public long getId_doctor() {
		return _id_doctor;
	}

	@Override
	public void setId_doctor(long id_doctor) {
		_id_doctor = id_doctor;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Patients.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Patients toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Patients)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PatientsImpl patientsImpl = new PatientsImpl();

		patientsImpl.setId_patient(getId_patient());
		patientsImpl.setName(getName());
		patientsImpl.setAddress(getAddress());
		patientsImpl.setPhonenumber(getPhonenumber());
		patientsImpl.setDepartment(getDepartment());
		patientsImpl.setSymptoms(getSymptoms());
		patientsImpl.setGender(getGender());
		patientsImpl.setId_doctor(getId_doctor());

		patientsImpl.resetOriginalValues();

		return patientsImpl;
	}

	@Override
	public int compareTo(Patients patients) {
		long primaryKey = patients.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Patients)) {
			return false;
		}

		Patients patients = (Patients)obj;

		long primaryKey = patients.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Patients> toCacheModel() {
		PatientsCacheModel patientsCacheModel = new PatientsCacheModel();

		patientsCacheModel.id_patient = getId_patient();

		patientsCacheModel.name = getName();

		String name = patientsCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			patientsCacheModel.name = null;
		}

		patientsCacheModel.address = getAddress();

		String address = patientsCacheModel.address;

		if ((address != null) && (address.length() == 0)) {
			patientsCacheModel.address = null;
		}

		patientsCacheModel.phonenumber = getPhonenumber();

		String phonenumber = patientsCacheModel.phonenumber;

		if ((phonenumber != null) && (phonenumber.length() == 0)) {
			patientsCacheModel.phonenumber = null;
		}

		patientsCacheModel.department = getDepartment();

		String department = patientsCacheModel.department;

		if ((department != null) && (department.length() == 0)) {
			patientsCacheModel.department = null;
		}

		patientsCacheModel.symptoms = getSymptoms();

		String symptoms = patientsCacheModel.symptoms;

		if ((symptoms != null) && (symptoms.length() == 0)) {
			patientsCacheModel.symptoms = null;
		}

		patientsCacheModel.gender = getGender();

		String gender = patientsCacheModel.gender;

		if ((gender != null) && (gender.length() == 0)) {
			patientsCacheModel.gender = null;
		}

		patientsCacheModel.id_doctor = getId_doctor();

		return patientsCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{id_patient=");
		sb.append(getId_patient());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", address=");
		sb.append(getAddress());
		sb.append(", phonenumber=");
		sb.append(getPhonenumber());
		sb.append(", department=");
		sb.append(getDepartment());
		sb.append(", symptoms=");
		sb.append(getSymptoms());
		sb.append(", gender=");
		sb.append(getGender());
		sb.append(", id_doctor=");
		sb.append(getId_doctor());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("org.pn.model.Patients");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id_patient</column-name><column-value><![CDATA[");
		sb.append(getId_patient());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>address</column-name><column-value><![CDATA[");
		sb.append(getAddress());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>phonenumber</column-name><column-value><![CDATA[");
		sb.append(getPhonenumber());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>department</column-name><column-value><![CDATA[");
		sb.append(getDepartment());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>symptoms</column-name><column-value><![CDATA[");
		sb.append(getSymptoms());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>gender</column-name><column-value><![CDATA[");
		sb.append(getGender());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>id_doctor</column-name><column-value><![CDATA[");
		sb.append(getId_doctor());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Patients.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			Patients.class
		};
	private long _id_patient;
	private String _name;
	private String _address;
	private String _phonenumber;
	private String _department;
	private String _symptoms;
	private String _gender;
	private long _id_doctor;
	private Patients _escapedModel;
}