/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.pn.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.pn.model.RoomPatient;
import org.pn.model.RoomPatientModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the RoomPatient service. Represents a row in the &quot;hos_roompatient&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.pn.model.RoomPatientModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RoomPatientImpl}.
 * </p>
 *
 * @author thuctap
 * @see RoomPatientImpl
 * @see org.pn.model.RoomPatient
 * @see org.pn.model.RoomPatientModel
 * @generated
 */
public class RoomPatientModelImpl extends BaseModelImpl<RoomPatient>
	implements RoomPatientModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a room patient model instance should use the {@link org.pn.model.RoomPatient} interface instead.
	 */
	public static final String TABLE_NAME = "hos_roompatient";
	public static final Object[][] TABLE_COLUMNS = {
			{ "room_no", Types.BIGINT },
			{ "status", Types.VARCHAR },
			{ "id_patient", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table hos_roompatient (room_no LONG not null primary key,status VARCHAR(75) null,id_patient LONG)";
	public static final String TABLE_SQL_DROP = "drop table hos_roompatient";
	public static final String ORDER_BY_JPQL = " ORDER BY roomPatient.room_no ASC";
	public static final String ORDER_BY_SQL = " ORDER BY hos_roompatient.room_no ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.pn.model.RoomPatient"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.pn.model.RoomPatient"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.pn.model.RoomPatient"));

	public RoomPatientModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _room_no;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setRoom_no(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _room_no;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return RoomPatient.class;
	}

	@Override
	public String getModelClassName() {
		return RoomPatient.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("room_no", getRoom_no());
		attributes.put("status", getStatus());
		attributes.put("id_patient", getId_patient());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long room_no = (Long)attributes.get("room_no");

		if (room_no != null) {
			setRoom_no(room_no);
		}

		String status = (String)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		Long id_patient = (Long)attributes.get("id_patient");

		if (id_patient != null) {
			setId_patient(id_patient);
		}
	}

	@Override
	public long getRoom_no() {
		return _room_no;
	}

	@Override
	public void setRoom_no(long room_no) {
		_room_no = room_no;
	}

	@Override
	public String getStatus() {
		if (_status == null) {
			return StringPool.BLANK;
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		_status = status;
	}

	@Override
	public long getId_patient() {
		return _id_patient;
	}

	@Override
	public void setId_patient(long id_patient) {
		_id_patient = id_patient;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			RoomPatient.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public RoomPatient toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (RoomPatient)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RoomPatientImpl roomPatientImpl = new RoomPatientImpl();

		roomPatientImpl.setRoom_no(getRoom_no());
		roomPatientImpl.setStatus(getStatus());
		roomPatientImpl.setId_patient(getId_patient());

		roomPatientImpl.resetOriginalValues();

		return roomPatientImpl;
	}

	@Override
	public int compareTo(RoomPatient roomPatient) {
		long primaryKey = roomPatient.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof RoomPatient)) {
			return false;
		}

		RoomPatient roomPatient = (RoomPatient)obj;

		long primaryKey = roomPatient.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<RoomPatient> toCacheModel() {
		RoomPatientCacheModel roomPatientCacheModel = new RoomPatientCacheModel();

		roomPatientCacheModel.room_no = getRoom_no();

		roomPatientCacheModel.status = getStatus();

		String status = roomPatientCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			roomPatientCacheModel.status = null;
		}

		roomPatientCacheModel.id_patient = getId_patient();

		return roomPatientCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{room_no=");
		sb.append(getRoom_no());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", id_patient=");
		sb.append(getId_patient());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("org.pn.model.RoomPatient");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>room_no</column-name><column-value><![CDATA[");
		sb.append(getRoom_no());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>id_patient</column-name><column-value><![CDATA[");
		sb.append(getId_patient());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = RoomPatient.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			RoomPatient.class
		};
	private long _room_no;
	private String _status;
	private long _id_patient;
	private RoomPatient _escapedModel;
}