/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.pn.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.pn.model.Staffs;
import org.pn.model.StaffsModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Staffs service. Represents a row in the &quot;hos_staff&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.pn.model.StaffsModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StaffsImpl}.
 * </p>
 *
 * @author thuctap
 * @see StaffsImpl
 * @see org.pn.model.Staffs
 * @see org.pn.model.StaffsModel
 * @generated
 */
public class StaffsModelImpl extends BaseModelImpl<Staffs>
	implements StaffsModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a staffs model instance should use the {@link org.pn.model.Staffs} interface instead.
	 */
	public static final String TABLE_NAME = "hos_staff";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_staff", Types.BIGINT },
			{ "name", Types.VARCHAR },
			{ "gender", Types.VARCHAR },
			{ "department", Types.VARCHAR },
			{ "phonenumber", Types.VARCHAR },
			{ "id_doctor", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table hos_staff (id_staff LONG not null primary key,name VARCHAR(75) null,gender VARCHAR(75) null,department VARCHAR(75) null,phonenumber VARCHAR(75) null,id_doctor LONG)";
	public static final String TABLE_SQL_DROP = "drop table hos_staff";
	public static final String ORDER_BY_JPQL = " ORDER BY staffs.id_staff ASC";
	public static final String ORDER_BY_SQL = " ORDER BY hos_staff.id_staff ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.pn.model.Staffs"), true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.pn.model.Staffs"), true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.pn.model.Staffs"));

	public StaffsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id_staff;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId_staff(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id_staff;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Staffs.class;
	}

	@Override
	public String getModelClassName() {
		return Staffs.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id_staff", getId_staff());
		attributes.put("name", getName());
		attributes.put("gender", getGender());
		attributes.put("department", getDepartment());
		attributes.put("phonenumber", getPhonenumber());
		attributes.put("id_doctor", getId_doctor());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id_staff = (Long)attributes.get("id_staff");

		if (id_staff != null) {
			setId_staff(id_staff);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String gender = (String)attributes.get("gender");

		if (gender != null) {
			setGender(gender);
		}

		String department = (String)attributes.get("department");

		if (department != null) {
			setDepartment(department);
		}

		String phonenumber = (String)attributes.get("phonenumber");

		if (phonenumber != null) {
			setPhonenumber(phonenumber);
		}

		Long id_doctor = (Long)attributes.get("id_doctor");

		if (id_doctor != null) {
			setId_doctor(id_doctor);
		}
	}

	@Override
	public long getId_staff() {
		return _id_staff;
	}

	@Override
	public void setId_staff(long id_staff) {
		_id_staff = id_staff;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public String getGender() {
		if (_gender == null) {
			return StringPool.BLANK;
		}
		else {
			return _gender;
		}
	}

	@Override
	public void setGender(String gender) {
		_gender = gender;
	}

	@Override
	public String getDepartment() {
		if (_department == null) {
			return StringPool.BLANK;
		}
		else {
			return _department;
		}
	}

	@Override
	public void setDepartment(String department) {
		_department = department;
	}

	@Override
	public String getPhonenumber() {
		if (_phonenumber == null) {
			return StringPool.BLANK;
		}
		else {
			return _phonenumber;
		}
	}

	@Override
	public void setPhonenumber(String phonenumber) {
		_phonenumber = phonenumber;
	}

	@Override
	public long getId_doctor() {
		return _id_doctor;
	}

	@Override
	public void setId_doctor(long id_doctor) {
		_id_doctor = id_doctor;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Staffs.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Staffs toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Staffs)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		StaffsImpl staffsImpl = new StaffsImpl();

		staffsImpl.setId_staff(getId_staff());
		staffsImpl.setName(getName());
		staffsImpl.setGender(getGender());
		staffsImpl.setDepartment(getDepartment());
		staffsImpl.setPhonenumber(getPhonenumber());
		staffsImpl.setId_doctor(getId_doctor());

		staffsImpl.resetOriginalValues();

		return staffsImpl;
	}

	@Override
	public int compareTo(Staffs staffs) {
		long primaryKey = staffs.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Staffs)) {
			return false;
		}

		Staffs staffs = (Staffs)obj;

		long primaryKey = staffs.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Staffs> toCacheModel() {
		StaffsCacheModel staffsCacheModel = new StaffsCacheModel();

		staffsCacheModel.id_staff = getId_staff();

		staffsCacheModel.name = getName();

		String name = staffsCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			staffsCacheModel.name = null;
		}

		staffsCacheModel.gender = getGender();

		String gender = staffsCacheModel.gender;

		if ((gender != null) && (gender.length() == 0)) {
			staffsCacheModel.gender = null;
		}

		staffsCacheModel.department = getDepartment();

		String department = staffsCacheModel.department;

		if ((department != null) && (department.length() == 0)) {
			staffsCacheModel.department = null;
		}

		staffsCacheModel.phonenumber = getPhonenumber();

		String phonenumber = staffsCacheModel.phonenumber;

		if ((phonenumber != null) && (phonenumber.length() == 0)) {
			staffsCacheModel.phonenumber = null;
		}

		staffsCacheModel.id_doctor = getId_doctor();

		return staffsCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{id_staff=");
		sb.append(getId_staff());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", gender=");
		sb.append(getGender());
		sb.append(", department=");
		sb.append(getDepartment());
		sb.append(", phonenumber=");
		sb.append(getPhonenumber());
		sb.append(", id_doctor=");
		sb.append(getId_doctor());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("org.pn.model.Staffs");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id_staff</column-name><column-value><![CDATA[");
		sb.append(getId_staff());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>gender</column-name><column-value><![CDATA[");
		sb.append(getGender());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>department</column-name><column-value><![CDATA[");
		sb.append(getDepartment());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>phonenumber</column-name><column-value><![CDATA[");
		sb.append(getPhonenumber());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>id_doctor</column-name><column-value><![CDATA[");
		sb.append(getId_doctor());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Staffs.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] { Staffs.class };
	private long _id_staff;
	private String _name;
	private String _gender;
	private String _department;
	private String _phonenumber;
	private long _id_doctor;
	private Staffs _escapedModel;
}