/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.pn.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Bills service. Represents a row in the &quot;hos_bill&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.pn.model.impl.BillsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.pn.model.impl.BillsImpl}.
 * </p>
 *
 * @author thuctap
 * @see Bills
 * @see org.pn.model.impl.BillsImpl
 * @see org.pn.model.impl.BillsModelImpl
 * @generated
 */
public interface BillsModel extends BaseModel<Bills> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bills model instance should use the {@link Bills} interface instead.
	 */

	/**
	 * Returns the primary key of this bills.
	 *
	 * @return the primary key of this bills
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bills.
	 *
	 * @param primaryKey the primary key of this bills
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the bill_no of this bills.
	 *
	 * @return the bill_no of this bills
	 */
	public long getBill_no();

	/**
	 * Sets the bill_no of this bills.
	 *
	 * @param bill_no the bill_no of this bills
	 */
	public void setBill_no(long bill_no);

	/**
	 * Returns the patient_name of this bills.
	 *
	 * @return the patient_name of this bills
	 */
	@AutoEscape
	public String getPatient_name();

	/**
	 * Sets the patient_name of this bills.
	 *
	 * @param patient_name the patient_name of this bills
	 */
	public void setPatient_name(String patient_name);

	/**
	 * Returns the doctor_name of this bills.
	 *
	 * @return the doctor_name of this bills
	 */
	@AutoEscape
	public String getDoctor_name();

	/**
	 * Sets the doctor_name of this bills.
	 *
	 * @param doctor_name the doctor_name of this bills
	 */
	public void setDoctor_name(String doctor_name);

	/**
	 * Returns the bill_date of this bills.
	 *
	 * @return the bill_date of this bills
	 */
	public Date getBill_date();

	/**
	 * Sets the bill_date of this bills.
	 *
	 * @param bill_date the bill_date of this bills
	 */
	public void setBill_date(Date bill_date);

	/**
	 * Returns the amount of this bills.
	 *
	 * @return the amount of this bills
	 */
	public int getAmount();

	/**
	 * Sets the amount of this bills.
	 *
	 * @param amount the amount of this bills
	 */
	public void setAmount(int amount);

	/**
	 * Returns the id_patient of this bills.
	 *
	 * @return the id_patient of this bills
	 */
	public long getId_patient();

	/**
	 * Sets the id_patient of this bills.
	 *
	 * @param id_patient the id_patient of this bills
	 */
	public void setId_patient(long id_patient);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(org.pn.model.Bills bills);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.pn.model.Bills> toCacheModel();

	@Override
	public org.pn.model.Bills toEscapedModel();

	@Override
	public org.pn.model.Bills toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}