/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.pn.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Diagnosis service. Represents a row in the &quot;hos_diagnosis&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.pn.model.impl.DiagnosisModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.pn.model.impl.DiagnosisImpl}.
 * </p>
 *
 * @author thuctap
 * @see Diagnosis
 * @see org.pn.model.impl.DiagnosisImpl
 * @see org.pn.model.impl.DiagnosisModelImpl
 * @generated
 */
public interface DiagnosisModel extends BaseModel<Diagnosis> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a diagnosis model instance should use the {@link Diagnosis} interface instead.
	 */

	/**
	 * Returns the primary key of this diagnosis.
	 *
	 * @return the primary key of this diagnosis
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this diagnosis.
	 *
	 * @param primaryKey the primary key of this diagnosis
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the diagnosis_no of this diagnosis.
	 *
	 * @return the diagnosis_no of this diagnosis
	 */
	public long getDiagnosis_no();

	/**
	 * Sets the diagnosis_no of this diagnosis.
	 *
	 * @param diagnosis_no the diagnosis_no of this diagnosis
	 */
	public void setDiagnosis_no(long diagnosis_no);

	/**
	 * Returns the detail of this diagnosis.
	 *
	 * @return the detail of this diagnosis
	 */
	@AutoEscape
	public String getDetail();

	/**
	 * Sets the detail of this diagnosis.
	 *
	 * @param detail the detail of this diagnosis
	 */
	public void setDetail(String detail);

	/**
	 * Returns the remak of this diagnosis.
	 *
	 * @return the remak of this diagnosis
	 */
	@AutoEscape
	public String getRemak();

	/**
	 * Sets the remak of this diagnosis.
	 *
	 * @param remak the remak of this diagnosis
	 */
	public void setRemak(String remak);

	/**
	 * Returns the diagnosis_date of this diagnosis.
	 *
	 * @return the diagnosis_date of this diagnosis
	 */
	public Date getDiagnosis_date();

	/**
	 * Sets the diagnosis_date of this diagnosis.
	 *
	 * @param diagnosis_date the diagnosis_date of this diagnosis
	 */
	public void setDiagnosis_date(Date diagnosis_date);

	/**
	 * Returns the id_patient of this diagnosis.
	 *
	 * @return the id_patient of this diagnosis
	 */
	public long getId_patient();

	/**
	 * Sets the id_patient of this diagnosis.
	 *
	 * @param id_patient the id_patient of this diagnosis
	 */
	public void setId_patient(long id_patient);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(org.pn.model.Diagnosis diagnosis);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.pn.model.Diagnosis> toCacheModel();

	@Override
	public org.pn.model.Diagnosis toEscapedModel();

	@Override
	public org.pn.model.Diagnosis toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}