/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.pn.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Drug service. Represents a row in the &quot;hos_drug&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.pn.model.impl.DrugModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.pn.model.impl.DrugImpl}.
 * </p>
 *
 * @author thuctap
 * @see Drug
 * @see org.pn.model.impl.DrugImpl
 * @see org.pn.model.impl.DrugModelImpl
 * @generated
 */
public interface DrugModel extends BaseModel<Drug> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a drug model instance should use the {@link Drug} interface instead.
	 */

	/**
	 * Returns the primary key of this drug.
	 *
	 * @return the primary key of this drug
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this drug.
	 *
	 * @param primaryKey the primary key of this drug
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_drug of this drug.
	 *
	 * @return the id_drug of this drug
	 */
	public long getId_drug();

	/**
	 * Sets the id_drug of this drug.
	 *
	 * @param id_drug the id_drug of this drug
	 */
	public void setId_drug(long id_drug);

	/**
	 * Returns the name_medicine of this drug.
	 *
	 * @return the name_medicine of this drug
	 */
	@AutoEscape
	public String getName_medicine();

	/**
	 * Sets the name_medicine of this drug.
	 *
	 * @param name_medicine the name_medicine of this drug
	 */
	public void setName_medicine(String name_medicine);

	/**
	 * Returns the quantity of this drug.
	 *
	 * @return the quantity of this drug
	 */
	public int getQuantity();

	/**
	 * Sets the quantity of this drug.
	 *
	 * @param quantity the quantity of this drug
	 */
	public void setQuantity(int quantity);

	/**
	 * Returns the price of this drug.
	 *
	 * @return the price of this drug
	 */
	@AutoEscape
	public String getPrice();

	/**
	 * Sets the price of this drug.
	 *
	 * @param price the price of this drug
	 */
	public void setPrice(String price);

	/**
	 * Returns the expiration_date of this drug.
	 *
	 * @return the expiration_date of this drug
	 */
	public Date getExpiration_date();

	/**
	 * Sets the expiration_date of this drug.
	 *
	 * @param expiration_date the expiration_date of this drug
	 */
	public void setExpiration_date(Date expiration_date);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(org.pn.model.Drug drug);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.pn.model.Drug> toCacheModel();

	@Override
	public org.pn.model.Drug toEscapedModel();

	@Override
	public org.pn.model.Drug toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}