/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.pn.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Medicine service. Represents a row in the &quot;hos_medicine&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.pn.model.impl.MedicineModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.pn.model.impl.MedicineImpl}.
 * </p>
 *
 * @author thuctap
 * @see Medicine
 * @see org.pn.model.impl.MedicineImpl
 * @see org.pn.model.impl.MedicineModelImpl
 * @generated
 */
public interface MedicineModel extends BaseModel<Medicine> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a medicine model instance should use the {@link Medicine} interface instead.
	 */

	/**
	 * Returns the primary key of this medicine.
	 *
	 * @return the primary key of this medicine
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this medicine.
	 *
	 * @param primaryKey the primary key of this medicine
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_medicine of this medicine.
	 *
	 * @return the id_medicine of this medicine
	 */
	public long getId_medicine();

	/**
	 * Sets the id_medicine of this medicine.
	 *
	 * @param id_medicine the id_medicine of this medicine
	 */
	public void setId_medicine(long id_medicine);

	/**
	 * Returns the bill_no of this medicine.
	 *
	 * @return the bill_no of this medicine
	 */
	public long getBill_no();

	/**
	 * Sets the bill_no of this medicine.
	 *
	 * @param bill_no the bill_no of this medicine
	 */
	public void setBill_no(long bill_no);

	/**
	 * Returns the id_drug of this medicine.
	 *
	 * @return the id_drug of this medicine
	 */
	public long getId_drug();

	/**
	 * Sets the id_drug of this medicine.
	 *
	 * @param id_drug the id_drug of this medicine
	 */
	public void setId_drug(long id_drug);

	/**
	 * Returns the quantity of this medicine.
	 *
	 * @return the quantity of this medicine
	 */
	public int getQuantity();

	/**
	 * Sets the quantity of this medicine.
	 *
	 * @param quantity the quantity of this medicine
	 */
	public void setQuantity(int quantity);

	/**
	 * Returns the remark of this medicine.
	 *
	 * @return the remark of this medicine
	 */
	@AutoEscape
	public String getRemark();

	/**
	 * Sets the remark of this medicine.
	 *
	 * @param remark the remark of this medicine
	 */
	public void setRemark(String remark);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(org.pn.model.Medicine medicine);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.pn.model.Medicine> toCacheModel();

	@Override
	public org.pn.model.Medicine toEscapedModel();

	@Override
	public org.pn.model.Medicine toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}