/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.pn.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Patients service. Represents a row in the &quot;hos_patient&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.pn.model.impl.PatientsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.pn.model.impl.PatientsImpl}.
 * </p>
 *
 * @author thuctap
 * @see Patients
 * @see org.pn.model.impl.PatientsImpl
 * @see org.pn.model.impl.PatientsModelImpl
 * @generated
 */
public interface PatientsModel extends BaseModel<Patients> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a patients model instance should use the {@link Patients} interface instead.
	 */

	/**
	 * Returns the primary key of this patients.
	 *
	 * @return the primary key of this patients
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this patients.
	 *
	 * @param primaryKey the primary key of this patients
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_patient of this patients.
	 *
	 * @return the id_patient of this patients
	 */
	public long getId_patient();

	/**
	 * Sets the id_patient of this patients.
	 *
	 * @param id_patient the id_patient of this patients
	 */
	public void setId_patient(long id_patient);

	/**
	 * Returns the name of this patients.
	 *
	 * @return the name of this patients
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this patients.
	 *
	 * @param name the name of this patients
	 */
	public void setName(String name);

	/**
	 * Returns the address of this patients.
	 *
	 * @return the address of this patients
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this patients.
	 *
	 * @param address the address of this patients
	 */
	public void setAddress(String address);

	/**
	 * Returns the phonenumber of this patients.
	 *
	 * @return the phonenumber of this patients
	 */
	@AutoEscape
	public String getPhonenumber();

	/**
	 * Sets the phonenumber of this patients.
	 *
	 * @param phonenumber the phonenumber of this patients
	 */
	public void setPhonenumber(String phonenumber);

	/**
	 * Returns the department of this patients.
	 *
	 * @return the department of this patients
	 */
	@AutoEscape
	public String getDepartment();

	/**
	 * Sets the department of this patients.
	 *
	 * @param department the department of this patients
	 */
	public void setDepartment(String department);

	/**
	 * Returns the symptoms of this patients.
	 *
	 * @return the symptoms of this patients
	 */
	@AutoEscape
	public String getSymptoms();

	/**
	 * Sets the symptoms of this patients.
	 *
	 * @param symptoms the symptoms of this patients
	 */
	public void setSymptoms(String symptoms);

	/**
	 * Returns the gender of this patients.
	 *
	 * @return the gender of this patients
	 */
	@AutoEscape
	public String getGender();

	/**
	 * Sets the gender of this patients.
	 *
	 * @param gender the gender of this patients
	 */
	public void setGender(String gender);

	/**
	 * Returns the id_doctor of this patients.
	 *
	 * @return the id_doctor of this patients
	 */
	public long getId_doctor();

	/**
	 * Sets the id_doctor of this patients.
	 *
	 * @param id_doctor the id_doctor of this patients
	 */
	public void setId_doctor(long id_doctor);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(org.pn.model.Patients patients);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.pn.model.Patients> toCacheModel();

	@Override
	public org.pn.model.Patients toEscapedModel();

	@Override
	public org.pn.model.Patients toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}