/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.pn.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the RoomPatient service. Represents a row in the &quot;hos_roompatient&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.pn.model.impl.RoomPatientModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.pn.model.impl.RoomPatientImpl}.
 * </p>
 *
 * @author thuctap
 * @see RoomPatient
 * @see org.pn.model.impl.RoomPatientImpl
 * @see org.pn.model.impl.RoomPatientModelImpl
 * @generated
 */
public interface RoomPatientModel extends BaseModel<RoomPatient> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a room patient model instance should use the {@link RoomPatient} interface instead.
	 */

	/**
	 * Returns the primary key of this room patient.
	 *
	 * @return the primary key of this room patient
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this room patient.
	 *
	 * @param primaryKey the primary key of this room patient
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the room_no of this room patient.
	 *
	 * @return the room_no of this room patient
	 */
	public long getRoom_no();

	/**
	 * Sets the room_no of this room patient.
	 *
	 * @param room_no the room_no of this room patient
	 */
	public void setRoom_no(long room_no);

	/**
	 * Returns the status of this room patient.
	 *
	 * @return the status of this room patient
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this room patient.
	 *
	 * @param status the status of this room patient
	 */
	public void setStatus(String status);

	/**
	 * Returns the id_patient of this room patient.
	 *
	 * @return the id_patient of this room patient
	 */
	public long getId_patient();

	/**
	 * Sets the id_patient of this room patient.
	 *
	 * @param id_patient the id_patient of this room patient
	 */
	public void setId_patient(long id_patient);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(org.pn.model.RoomPatient roomPatient);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.pn.model.RoomPatient> toCacheModel();

	@Override
	public org.pn.model.RoomPatient toEscapedModel();

	@Override
	public org.pn.model.RoomPatient toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}