/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.pn.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Staffs service. Represents a row in the &quot;hos_staff&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.pn.model.impl.StaffsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.pn.model.impl.StaffsImpl}.
 * </p>
 *
 * @author thuctap
 * @see Staffs
 * @see org.pn.model.impl.StaffsImpl
 * @see org.pn.model.impl.StaffsModelImpl
 * @generated
 */
public interface StaffsModel extends BaseModel<Staffs> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a staffs model instance should use the {@link Staffs} interface instead.
	 */

	/**
	 * Returns the primary key of this staffs.
	 *
	 * @return the primary key of this staffs
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this staffs.
	 *
	 * @param primaryKey the primary key of this staffs
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_staff of this staffs.
	 *
	 * @return the id_staff of this staffs
	 */
	public long getId_staff();

	/**
	 * Sets the id_staff of this staffs.
	 *
	 * @param id_staff the id_staff of this staffs
	 */
	public void setId_staff(long id_staff);

	/**
	 * Returns the name of this staffs.
	 *
	 * @return the name of this staffs
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this staffs.
	 *
	 * @param name the name of this staffs
	 */
	public void setName(String name);

	/**
	 * Returns the gender of this staffs.
	 *
	 * @return the gender of this staffs
	 */
	@AutoEscape
	public String getGender();

	/**
	 * Sets the gender of this staffs.
	 *
	 * @param gender the gender of this staffs
	 */
	public void setGender(String gender);

	/**
	 * Returns the department of this staffs.
	 *
	 * @return the department of this staffs
	 */
	@AutoEscape
	public String getDepartment();

	/**
	 * Sets the department of this staffs.
	 *
	 * @param department the department of this staffs
	 */
	public void setDepartment(String department);

	/**
	 * Returns the phonenumber of this staffs.
	 *
	 * @return the phonenumber of this staffs
	 */
	@AutoEscape
	public String getPhonenumber();

	/**
	 * Sets the phonenumber of this staffs.
	 *
	 * @param phonenumber the phonenumber of this staffs
	 */
	public void setPhonenumber(String phonenumber);

	/**
	 * Returns the id_doctor of this staffs.
	 *
	 * @return the id_doctor of this staffs
	 */
	public long getId_doctor();

	/**
	 * Sets the id_doctor of this staffs.
	 *
	 * @param id_doctor the id_doctor of this staffs
	 */
	public void setId_doctor(long id_doctor);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(org.pn.model.Staffs staffs);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.pn.model.Staffs> toCacheModel();

	@Override
	public org.pn.model.Staffs toEscapedModel();

	@Override
	public org.pn.model.Staffs toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}