/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.pn.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Status service. Represents a row in the &quot;hos_status&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.pn.model.impl.StatusModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.pn.model.impl.StatusImpl}.
 * </p>
 *
 * @author thuctap
 * @see Status
 * @see org.pn.model.impl.StatusImpl
 * @see org.pn.model.impl.StatusModelImpl
 * @generated
 */
public interface StatusModel extends BaseModel<Status> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a status model instance should use the {@link Status} interface instead.
	 */

	/**
	 * Returns the primary key of this status.
	 *
	 * @return the primary key of this status
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this status.
	 *
	 * @param primaryKey the primary key of this status
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the status_no of this status.
	 *
	 * @return the status_no of this status
	 */
	public long getStatus_no();

	/**
	 * Sets the status_no of this status.
	 *
	 * @param status_no the status_no of this status
	 */
	public void setStatus_no(long status_no);

	/**
	 * Returns the status_detail of this status.
	 *
	 * @return the status_detail of this status
	 */
	@AutoEscape
	public String getStatus_detail();

	/**
	 * Sets the status_detail of this status.
	 *
	 * @param status_detail the status_detail of this status
	 */
	public void setStatus_detail(String status_detail);

	/**
	 * Returns the id_patient of this status.
	 *
	 * @return the id_patient of this status
	 */
	public long getId_patient();

	/**
	 * Sets the id_patient of this status.
	 *
	 * @param id_patient the id_patient of this status
	 */
	public void setId_patient(long id_patient);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(org.pn.model.Status status);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.pn.model.Status> toCacheModel();

	@Override
	public org.pn.model.Status toEscapedModel();

	@Override
	public org.pn.model.Status toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}